In [1]:
def add(a,b):
  return a+b

In [2]:
x=20
y=20

res=add(x,y)
print(res)

40


In [5]:
def welcome():
  print("welcome to python lab")
welcome()

welcome to python lab


In [6]:
def square(n):
  return n*n
print(square(5))

25


In [1]:
import numpy as np
n=int(input("How many numbers"))
num=[]
for i in range(n):
  x=int(input("Enter number"))
  num.append(x)

arr=np.array(num)
print("Type:",type(arr))
print("Numpy Array:",arr)
print("Array shape:",arr.shape)
print("Array dim:",arr.ndim)
print("Array type:",arr.dtype)

How many numbers4
Enter number2
Enter number3
Enter number4
Enter number6
Type: <class 'numpy.ndarray'>
Numpy Array: [2 3 4 6]
Array shape: (4,)
Array dim: 1
Array type: int64


In [4]:
def create_Array(n):
  num=[]
  for i in range(n):
   x=int(input("Enter number"))
   num.append(x)
  return np.array(num)

y=int(input("How many numbers"))
arr=create_Array(y)
print(arr)


How many numbers3
Enter number5
Enter number6
Enter number4
[5 6 4]


In [5]:
def student(name,age):
  print("Name:",name)
  print("Age:",age)

student(name="John",age=20)

Name: John
Age: 20


In [7]:
def add(*num):
  total=0
  for i in num:
    total+=i
  return total

In [11]:
print(add(10,20))
print(add(10,20,30))

30
60


In [12]:
def student(**details):
  print(details)

student(name="Rahul",age=20,city="Agra")


{'name': 'Rahul', 'age': 20, 'city': 'Agra'}


Reshaping Arrays

In [14]:
import numpy as np
data=np.arange(1,13)
print("original data shape",data.shape)
a=data.reshape(3,4)
print("3x4 \n",a)
c=data.reshape(2,-1)
print("2xinfer \n",c)

original data shape (12,)
3x4 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2xinfer 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Flatten() and ravel()

In [16]:
data=np.array([[1,2,3],[4,5,6]])
print(data.ndim)
flat1=data.flatten()
print("flat1 shape:",flat1.shape)
flat2=data.ravel()
print("flat2 shape:",flat2.shape)

2
flat1 shape: (6,)
flat2 shape: (6,)


np.concatenate()
np.vstack()
np.hstack()

In [19]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(np.concatenate((a,b)))

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Vectorization

In [21]:
data= np.array([10,20,30,40,50])
res=[]
for i in data:
 vec_data=data*2
print(vec_data)

[ 20  40  60  80 100]


In [22]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)


[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]


In [24]:
marks=np.array([50,60,70,80,90])
print(f'Add5:{marks+5}')
print(f'Sub5:{marks-5}')
print(f'Mul5:{marks*5}')


Add5:[55 65 75 85 95]
Sub5:[45 55 65 75 85]
Mul5:[250 300 350 400 450]


In [26]:
marks=np.array([20,40,50,60,70,80,90])
passed= marks>=40
between=marks[(marks>=50) & (marks<=80)]
print(f'mask for marks>=40:{passed}')
print(f'Passing marks:{marks[passed]}')
print(f'Marks between 50 and 80:{between}')
print(passed)
print(between)

mask for marks>=40:[False  True  True  True  True  True  True]
Passing marks:[40 50 60 70 80 90]
Marks between 50 and 80:[50 60 70 80]
[False  True  True  True  True  True  True]
[50 60 70 80]


Broadcasting

In [27]:
arr=np.array([1,2,3])
res=arr+1
print(res)

[2 3 4]


In [28]:
a=np.array([12,34,53,69])
b=np.array(["Adult","Minor"])
res=np.where(a>18,b[0],b[1])
print(res)


['Minor' 'Adult' 'Adult' 'Adult']


In [29]:
m=np.array([[2,3],[5,6]])
v=np.array([10,20])
res=m*v
print(res)

[[ 20  60]
 [ 50 120]]
